/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.109
 * Generated at: 2025-12-16 11:19:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/NanoChip/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1761057346083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Register</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("          href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div style=\"margin-top: 50px\"\r\n");
      out.write("         class=\"mainbox col-md-4 col-md-offset-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"panel panel-info\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"panel-heading\">\r\n");
      out.write("                <div class=\"panel-title\">Register New User</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"panel-body\" style=\"padding-top:30px\">\r\n");
      out.write("\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\"\r\n");
      out.write("                      method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("                    <!-- Username -->\r\n");
      out.write("                    <div class=\"input-group\" style=\"margin-bottom:25px\">\r\n");
      out.write("                        <span class=\"input-group-addon\">\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"text\" name=\"username\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Username\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Password -->\r\n");
      out.write("                    <div class=\"input-group\" style=\"margin-bottom:25px\">\r\n");
      out.write("                        <span class=\"input-group-addon\">\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-lock\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"password\" name=\"password\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Confirm Password -->\r\n");
      out.write("                    <div class=\"input-group\" style=\"margin-bottom:25px\">\r\n");
      out.write("                        <span class=\"input-group-addon\">\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-lock\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"password\" name=\"confirmPassword\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Confirm Password\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- First Name -->\r\n");
      out.write("                    <div class=\"input-group\" style=\"margin-bottom:25px\">\r\n");
      out.write("                        <span class=\"input-group-addon\">\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"text\" name=\"firstName\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"First Name\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Last Name -->\r\n");
      out.write("                    <div class=\"input-group\" style=\"margin-bottom:25px\">\r\n");
      out.write("                        <span class=\"input-group-addon\">\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"text\" name=\"lastName\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Last Name\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Email -->\r\n");
      out.write("                    <div class=\"input-group\" style=\"margin-bottom:25px\">\r\n");
      out.write("                        <span class=\"input-group-addon\">\r\n");
      out.write("                            <i class=\"glyphicon glyphicon-envelope\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"email\" name=\"email\"\r\n");
      out.write("                               class=\"form-control\"\r\n");
      out.write("                               placeholder=\"Email\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Button -->\r\n");
      out.write("                    <button type=\"submit\"\r\n");
      out.write("                            class=\"btn btn-primary btn-block\">\r\n");
      out.write("                        Register\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
